version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mailgun-hook"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rjad8cjg8aq5"
s3_prefix = "mailgun-hook"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
